version: 2

sources:
    - name: staging
      database: de-zoomcamp-338919
      schema: trips_yellow_taxi_data_all

      tables:
        - name: green_tripdata
        - name: yellow_tripdata